### ISSUE TITLE
Moved Zeta node to another VPS, bundle restore errors

### ISSUE THREAD

**Issue by labbitroma** [ambrosus/ambrosus-nop#176]
Hello,
I moved the node to another VPS following this guide https://github.com/ambrosus/community-wiki/wiki/Maintenance-Atlas.

When I check /nodeInfo I see the error `Failed to restore bundle: Cannot read property 'bundleStoreWrapperContract' of undefined` for every bundle.

**Comment by vpowler** [comment]
Please use the update.sh script located in ~/ambrosus-nop folder to update to the latest version.

**Comment by vpowler** [comment]
The problem is actually occurred in ambrosus-node and was successfully fixed.
