### ISSUE TITLE
Generated "state.json" file should have stricter permissions

### ISSUE THREAD

**Issue by hypnotortoise** [ambrosus/ambrosus-nop#38]
The generated JSON file with the private key included can be read by all users. This file should be only read-/writable by the user which creates it.

**Comment by gaia** [comment]
better yet, the file should be encrypted with a password. private key password would reside in RAM during node operation (already more secure than in a plain text file)

taking this further, a nano ledger would be required to sign TXs

PS: Tezos offers both options.
